### ISSUE TITLE
Landing Screen // Mockup and Implementation 

### ISSUE THREAD

**Issue by VhatAmI** [UMKCTeamSeven/HCIT7#11]
View of landing screen, team brainstorm

**Comment by DVGalarza** [comment]
These are the specific landing screen & menu details:

Splash Screen for App (Money Museum) -- 2 or 3 seconds
Then Menu screen with:
     Guided Tour (button)
     Money Mirror (button)

**Comment by VhatAmI** [comment]
@reggieroby this info with @ward-steven-umkc mock up will get you started

**Comment by DVGalarza** [comment]
<img width="253" alt="screenshot 2016-04-11 19 20 02" src="https://cloud.githubusercontent.com/assets/10988301/14446354/97c0e196-001a-11e6-8740-383ba5c8e703.png">

**Comment by DVGalarza** [comment]
https://moqups.com/dvgalarza/S7rVVP26/p:a16b2c2a4

**Comment by VhatAmI** [comment]
@DVGalarza can you present this on Monday and answer questions? I won't be able to make class. @reggieroby might have an app to mirror it ready
