### ISSUE TITLE
Mock up screens that match potential interactive panels 

### ISSUE THREAD

**Issue by VhatAmI** [UMKCTeamSeven/HCIT7#18]

**Comment by VhatAmI** [comment]
This is mock ups for exhibits that don't exist yet, 1 app screen and 1 exhibit screen per mock up

think about how the phone could interact with another large panel screen 

I'd like the entire team to try and think of at least one, or use an idea already talked about and make one for it.

**Comment by VhatAmI** [comment]
Once the iteration is over, we will decide which ones to implement in iteration 3

**Comment by ward-steven-umkc** [comment]
more mocks for money mirror using ipad... need help on color scheme edit if you wish

https://moqups.com/sgward94@gmail.com/Sv0e544p/p:a16b2c2a4

**Comment by VhatAmI** [comment]
JOHN CENA

**Comment by VhatAmI** [comment]
Moving to backlog, will do after Itr 3 if desired.

**Comment by VhatAmI** [comment]
Closing as won't fix as another team's idea now encompasses.
