### ISSUE TITLE
First Meeting -- Planning Iteration 1 

### ISSUE THREAD

**Issue by VhatAmI** [UMKCTeamSeven/HCIT7#4]
After class monday : notes below

**Comment by VhatAmI** [comment]
Review goals, confirm stories, story point

**Comment by VhatAmI** [comment]
Money shot
Guided tour
Interface with panels?

**Comment by ward-steven-umkc** [comment]
![usdollar100front](https://cloud.githubusercontent.com/assets/15387635/14290357/603273a2-fb24-11e5-8585-c75c5b43665e.jpg)

**Comment by ward-steven-umkc** [comment]
the old one was easier because it has the circle where the face is supposed to go.
