### ISSUE TITLE
Bill Types // Photoedited mockups 

### ISSUE THREAD

**Issue by VhatAmI** [UMKCTeamSeven/HCIT7#5]

**Comment by VhatAmI** [comment]
Currently we have a USA 100$ bill 

does the museum include non-US currency? If so should we include other bill types? 

USA 50$
USA 1000$ 
USA 20$
USA 10$

**Comment by VhatAmI** [comment]
http://www.getpaint.net/index.html or other photoediting tool 

Transparent backdrop in headspace 

Green Serial number reads HCI T7 UMKC S16 but has same spacing as original 
this makes it 12 digits instead of 11, and counterfeit

Discuss if we want to have a spot the counterfeit bill mode

**Comment by ward-steven-umkc** [comment]
no face bills for 1,5,10,20,50 added along with minor errors/room for errors on all of them for spot the mistake game
