### ISSUE TITLE
Views and Menu entry // Mockup  

### ISSUE THREAD

**Issue by VhatAmI** [UMKCTeamSeven/HCIT7#8]

**Comment by ward-steven-umkc** [comment]
[protoio_Treasury.pdf](https://github.com/UMKCTeamSeven/HCIT7/files/214115/protoio_Treasury.pdf)

**Comment by VhatAmI** [comment]
@reggieroby

**Comment by VhatAmI** [comment]
@reggieroby can you have app up Monday? @OmgxEric do you have a Mac? if So I'd like to have reggie show you how to get started sometime this week...
